// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5yu1DAIAiMXmZWB03ddZsZYgNmECRtwc',
    appId: '1:755892653855:web:3d959549607ea08be5aa2a',
    messagingSenderId: '755892653855',
    projectId: 'camnak-fishing',
    authDomain: 'camnak-fishing.firebaseapp.com',
    databaseURL: 'https://camnak-fishing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'camnak-fishing.firebasestorage.app',
    measurementId: 'G-VS4N2N7YGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6kIVBUQAtfYEr8OwV9LNnpLLGwOhMsg',
    appId: '1:755892653855:android:d6c35605b9cd07bae5aa2a',
    messagingSenderId: '755892653855',
    projectId: 'camnak-fishing',
    storageBucket: 'camnak-fishing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFEl_sc3GNZbQC4sMx_vCXvQV8zXcTyQ',
    appId: '1:755892653855:ios:6934a55a7621123ae5aa2a',
    messagingSenderId: '755892653855',
    projectId: 'camnak-fishing',
    storageBucket: 'camnak-fishing.firebasestorage.app',
    iosBundleId: 'com.example.camnakFishing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFEl_sc3GNZbQC4sMx_vCXvQV8zXcTyQ',
    appId: '1:755892653855:ios:6934a55a7621123ae5aa2a',
    messagingSenderId: '755892653855',
    projectId: 'camnak-fishing',
    storageBucket: 'camnak-fishing.firebasestorage.app',
    iosBundleId: 'com.example.camnakFishing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5yu1DAIAiMXmZWB03ddZsZYgNmECRtwc',
    appId: '1:755892653855:web:8984382903b5b638e5aa2a',
    messagingSenderId: '755892653855',
    projectId: 'camnak-fishing',
    authDomain: 'camnak-fishing.firebaseapp.com',
    storageBucket: 'camnak-fishing.firebasestorage.app',
    measurementId: 'G-GWRCDY1PS9',
  );
}
